syntax = "proto3";

package comms;

message Object {
  // Request Server to add local object
  message Add {
    string hostname = 1;

    // Only use if file is from a directory sync
    optional string parent_tree = 2;
    bool child_of_tree = 3;

    string path = 4;
    bool is_directory = 5;

    // All files and directories must have hashes
    bytes hash = 6;
  }

  // Server allowed the object to be synced
  message AddResponse {
    bytes object_id = 1;

    bool success = 2;
    optional AddError error = 3;

    enum AddError {
      AlreadySynced = 0;
      Unknown = 1;
    }
  }

  // Ask Server to remove object either using the path or object_id
  message Remove {
    string hostname = 1;

    oneof identifier {
      string path = 2;
      bytes object_id = 3;
    }
  }

  // Server allowed the object to be removed
  message RemoveResponse {
    bool success = 1;
    optional RemoveError error = 2;

    enum RemoveError {
      DoesNotExit = 0;
      InvalidParameters = 1;
      Unknown = 2;
    }
  }

  // Request a sync check
  message Sync {
    bytes object_id = 1;
    bytes hash = 2;
  }

  // Response of object Sync check
  message SyncResponse {
    bytes object_id = 1;
    SyncStatus status = 3;

    enum SyncStatus {
      Fine = 0;
      RemoteOutOfDate = 1;
      LocalOutOfDate = 2;
    }
  }

  // Response to a RemoteOutOfDate or LocalOutOfDate
  message SyncHashes {
    bytes object_id = 1;

    bytes object_hash = 2;
    repeated bytes hashes = 3;
  }

  // Request to get chunk
  message Chunk {
    bytes object_id = 1;

    uint32 chunk_offset = 2;
  }

  // Receive chunk
  message ChunkResponse {
    bytes object_id = 1;

    bytes chunk = 2;
  }
}

// Request Server to send all file's that are currently synced
message List {}

message ListResponse {
  repeated bytes id = 1;
  repeated string path = 2;
  repeated bool is_child = 3;
  repeated string parent_directory = 4;
}