syntax = "proto3";

package comms;

message Object {
  // Request Server to add local object
  message Add {
    string hostname = 1;

    // Only use if file is from a directory sync
    optional string parent_tree = 2;
    bool child_of_tree = 3;

    string path = 4;
    bool is_directory = 5;

    // All files and directories must have hashes
    uint64 hash = 6;

  }

  // Server allowed the object to be synced
  message AddResponse {
    bytes object_id = 1;
    string path = 2;

    bool success = 3;
    optional AddError error = 4;

    enum AddError {
      AlreadySynced = 0;
      Unknown = 1;
    }
  }

  // Ask Server to remove object either using the path or object_id
  message Remove {
    string hostname = 1;

    oneof identifier {
      string path = 2;
      bytes object_id = 3;
    }
  }

  // Server allowed the object to be removed
  message RemoveResponse {
    bool success = 1;
    optional RemoveError error = 2;

    enum RemoveError {
      DoesNotExit = 0;
      InvalidParameters = 1;
      Unknown = 2;
    }
  }

  // Request a status check
  message Status {
    bytes object_id = 1;
    // During add phase the object has no data yet, so we can tell the client we have nothing...
    optional uint64 hash = 2;
    optional uint64 modified_last = 3;
  }

  // Response of object Sync check
  message StatusResponse {
    bytes object_id = 1;
    ObjectState state = 3;

    enum ObjectState {
      Fine = 0;
      RemoteOutOfDate = 1;
      LocalOutOfDate = 2;
      Deleted = 3;
    }
  }

  message Sync {
    bytes object_id = 1;
  }

  // Response to a Sync
  message SyncResponse {
    bytes object_id = 1;

    uint64 object_hash = 2;
    repeated uint64 hashes = 3;
  }

  // Request to get chunk
  message Chunk {
    bytes object_id = 1;
    uint32 chunk_offset = 2;
  }

  // Receive chunk
  message ChunkResponse {
    bytes object_id = 1;

    uint32 chunk_offset = 2;
    bytes chunk = 3;
  }
}

// Request Server to send all file's that are currently synced
message List {}

message ListResponse {
  repeated bytes object_id = 1;
  repeated string path = 2;
  repeated bool is_child = 3;
  repeated string parent_directory = 4;
}